/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_iret_sfq_SFQueueClientLocal */

#ifndef _Included_jp_co_iret_sfq_SFQueueClientLocal
#define _Included_jp_co_iret_sfq_SFQueueClientLocal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_iret_sfq_SFQueueClientLocal
 * Method:    wrap_sfq_push
 * Signature: (Ljava/util/Map;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_co_iret_sfq_SFQueueClientLocal_wrap_1sfq_1push
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_co_iret_sfq_SFQueueClientLocal
 * Method:    warp_sfq_takeout
 * Signature: (Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_jp_co_iret_sfq_SFQueueClientLocal_warp_1sfq_1takeout
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
