/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_iret_sfq_SFQueueClientLocal */

#ifndef _Included_jp_co_iret_sfq_SFQueueClientLocal
#define _Included_jp_co_iret_sfq_SFQueueClientLocal
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_co_iret_sfq_SFQueueClientLocal_SFQ_RC_SUCCESS
#define jp_co_iret_sfq_SFQueueClientLocal_SFQ_RC_SUCCESS 0L
#undef jp_co_iret_sfq_SFQueueClientLocal_SFQ_RC_FATAL_MIN
#define jp_co_iret_sfq_SFQueueClientLocal_SFQ_RC_FATAL_MIN 21L
/*
 * Class:     jp_co_iret_sfq_SFQueueClientLocal
 * Method:    wrap_sfq_push
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_iret_sfq_SFQueueClientLocal_wrap_1sfq_1push
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     jp_co_iret_sfq_SFQueueClientLocal
 * Method:    warp_sfq_takeout
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_iret_sfq_SFQueueClientLocal_warp_1sfq_1takeout
  (JNIEnv *, jobject, jstring, jstring, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
